version: "3.1"

services:
  mysql:
    image: mysql:5.7
    container_name: endouble-db
    tty: true
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - "3306:3306"

  webserver:
    build: docker/nginx/
    container_name: endouble-nginx
    restart: on-failure
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/api
      - ./logs/nginx/:/var/log/nginx:cached
      - ./docker/nginx/endoubleapi.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - mysql
      - php-fpm

  memcached:
    image: memcached:alpine
    container_name: endouble-memcached
    restart: on-failure
    tty: true
    links:
      - php-fpm

  php-fpm:
    build: docker/php/
    container_name: endouble-php-fpm
    tty: true
    restart: on-failure
    working_dir: /var/www/api
    links:
      - mysql
    volumes:
      - ./:/var/www/api

#Volumes
volumes:
  dbdata:
    driver: local
