imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
        throw: false
    cache:
        default_memcached_provider: '%memcached_host%'
        pools:
            app.cache.items:
                adapter: cache.adapter.memcached
                public: true
                default_lifetime: '%memcached_expire%'

fos_rest:
    disable_csrf_role: ROLE_API
    routing_loader:
        default_format: json
        include_format: false
    exception:
        enabled: false
        exception_controller: null
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': 405
            'Symfony\Component\Debug\Exception\FatalErrorException': 500
        messages:
            'Symfony\Component\Debug\Exception\FatalErrorException': false
            'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException': true
    view:
        view_response_listener: force
        formats:
            json: true
            html: false
        force_redirects:
            json: true
            html: false
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=1.1', 'application/json;version=1.2']
    param_fetcher_listener: true
    format_listener:
        rules:
            - { path: ^/, priorities: [ json ], fallback_format: json, prefer_extension: false }
    body_listener: true

sensio_framework_extra:
    request:
        converters: true
        disable: ['doctrine.orm', 'datetime']
    router:
        annotations: false
    view:
        annotations: true
