# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    guzzle.client:
        class: GuzzleHttp\Client
        public: true

    http.spacex.launch.adapter:
        class: Endouble\Engine\Infrastructure\Service\SpacexAdapter\HttpLaunchAdapter
        public: true
        arguments:
            $client: '@guzzle.client'

    http.xkcd.comic.adapter:
        class: Endouble\Engine\Infrastructure\Service\XkcdAdapter\HttpComicAdapter
        public: true
        arguments:
            $client: '@guzzle.client'

    endouble.application.create_items_from_all_spacex_past_launches:
        class: Endouble\Engine\Application\CreateItemsFromPastLaunches\CreateItemsFromPastLaunchesCommandHandler
        public: true
        arguments:
            $itemService: '@endouble.item.translating.service'
            $cacheItemPool: '@app.cache.items'

    endouble.application.create_items_from_all_xkcd_comics:
        class: Endouble\Engine\Application\CreateItemsFromAllXkcdComics\CreateItemsFromAllXkcdComicsCommandHandler
        public: true
        arguments:
            $itemService: '@endouble.item.translating.service'
            $cacheItemPool: '@app.cache.items'

    endouble.item.translating.service:
        class: Endouble\Engine\Infrastructure\Service\TranslatingItemService
        public: true
        arguments:
            $launchAdapter: '@http.spacex.launch.adapter'
            $comicAdapter: '@http.xkcd.comic.adapter'
