items:
    type: rest
    defaults: {_format: json}
    resource: ApiBundle\Controller\ItemController

healthcheck:
    type: rest
    defaults: {_format: json}
    resource: ApiBundle\Controller\HealthCheckController
